---
- hosts: routers
  gather_facts: false
  connection: local

  tasks:
    - name: Set Interface Description
      ios_config:
        lines:
          - description - Configured by Ansible
        parents: Interface GigabitEthernet0/0  