---
- hosts: all
  gather_facts: false
  connection: local

  tasks:
   - name: configure the login banner
     ios_banner:
        banner: login
        text: |
          ***** Warning *****

          This is a secure system

          Access is forbidden

          No access is permitted without permission

          ***** Warning *****
        state: present
